# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  wallet:
    image: wallet
    build:
      context: .
      dockerfile: src/Wallet.Web/Dockerfile
    ports:
      - 80